spring.application.name=ai.assistance

server.address=0.0.0.0

spring.ai.google.genai.api-key=${GEMINI_API_KEY}

spring.ai.google.genai.chat.options.model=${GEMINI_CHAT_MODEL}
spring.ai.google.genai.chat.options.temperature=0.3
spring.ai.google.genai.chat.options.max-output-tokens=2000



spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}

spring.ai.google.genai.embedding.text.model=gemini-embedding-001

spring.ai.model.embedding.text=${GEMINI_CHAT_EMBEDDING_MODEL}
# ==========================================
# MongoDB Atlas
# ==========================================

spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=${MONGODB_DATABASE}

# ==========================================
# Spring AI - MongoDB Atlas Vector Store
# ==========================================

spring.ai.vectorstore.mongodb.initialize-schema=true

spring.ai.vectorstore.mongodb.collection-name=vector_store

spring.ai.vectorstore.mongodb.index-name=vector_index

spring.ai.vectorstore.mongodb.path-name=embedding
